---
project_name: operator

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: kubewg-net
    name: "{{ .ProjectName }}"

dockers:
  - image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-arm64"
    use: buildx
    goarch: arm64
    extra_files:
      - hack/passwd
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kubewg-{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
      - --label=org.opencontainers.image.url=https://kubewg.net
      - --label=org.opencontainers.image.source=https://github.com/kubewg-net/operator
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v1"
    use: buildx
    goarch: amd64
    extra_files:
      - hack/passwd
    goamd64: v1
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kubewg-{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
      - --label=org.opencontainers.image.url=https://kubewg.net
      - --label=org.opencontainers.image.source=https://github.com/kubewg-net/operator
      - "--platform=linux/amd64/v1"
  - image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v2"
    use: buildx
    goarch: amd64
    extra_files:
      - hack/passwd
    goamd64: v2
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kubewg-{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
      - --label=org.opencontainers.image.url=https://kubewg.net
      - --label=org.opencontainers.image.source=https://github.com/kubewg-net/operator
      - "--platform=linux/amd64/v2"
  - image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v3"
    use: buildx
    goarch: amd64
    extra_files:
      - hack/passwd
    goamd64: v3
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kubewg-{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
      - --label=org.opencontainers.image.url=https://kubewg.net
      - --label=org.opencontainers.image.source=https://github.com/kubewg-net/operator
      - "--platform=linux/amd64/v3"
  - image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v4"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v4"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v4"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v4"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v4"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v4"
    use: buildx
    goarch: amd64
    extra_files:
      - hack/passwd
    goamd64: v4
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=kubewg-{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
      - --label=org.opencontainers.image.url=https://kubewg.net
      - --label=org.opencontainers.image.source=https://github.com/kubewg-net/operator
      - "--platform=linux/amd64/v4"

docker_manifests:
  - name_template: "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
  - name_template: "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}-amd64v4"
  - name_template: "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v4"
  - name_template: "ghcr.io/kubewg-net/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v1"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v2"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v3"
      - "ghcr.io/kubewg-net/{{ .ProjectName }}:latest-amd64v4"

  - name_template: "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
  - name_template: "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}-amd64v4"
  - name_template: "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64v4"
  - name_template: "docker.io/kubewg/{{ .ProjectName }}:latest"
    image_templates:
      - "docker.io/kubewg/{{ .ProjectName }}:latest-arm64"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v1"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v2"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v3"
      - "docker.io/kubewg/{{ .ProjectName }}:latest-amd64v4"

builds:
  - main: ./cmd/main.go
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    goamd64:
      - v1
      - v2
      - v3
      - v4
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
    flags:
      - -trimpath

milestones:
  - close: true
