# permissions for end users to view networks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubewg
    app.kubernetes.io/managed-by: kustomize
  name: network-viewer-role
rules:
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - networks/status
  verbs:
  - get
