# permissions for end users to edit peers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubewg
    app.kubernetes.io/managed-by: kustomize
  name: peer-editor-role
rules:
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - peers/status
  verbs:
  - get
