# permissions for end users to view peers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubewg
    app.kubernetes.io/managed-by: kustomize
  name: peer-viewer-role
rules:
- apiGroups:
  - kubewg.net
  resources:
  - peers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubewg.net
  resources:
  - peers/status
  verbs:
  - get
