---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - peers/finalizers
  verbs:
  - update
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - peers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - routers/finalizers
  verbs:
  - update
- apiGroups:
  - kubewg.mcswain.dev
  resources:
  - routers/status
  verbs:
  - get
  - patch
  - update
