# permissions for end users to edit routers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubewg
    app.kubernetes.io/managed-by: kustomize
  name: router-editor-role
rules:
- apiGroups:
  - kubewg.net
  resources:
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewg.net
  resources:
  - routers/status
  verbs:
  - get
