apiVersion: kubewg.mcswain.dev/v1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: kubewg
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
  # TODO(user): Add fields here
