name: Go Checks
on: pull_request

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: ensure generated files
        run: make manifests generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: test
        run: make test
  test-e2e:
    name: test-e2e
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Supported versions at https://kubernetes.io/releases/
        version:
        - v1.27.14 # EOL 2024-06-28
        - v1.28.10 # EOL 2024-10-28
        - v1.29.5 # EOL 2025-02-28
        - v1.30.1 # EOL 2025-06-28
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:${{ matrix.version }}
      - name: test-e2e
        run: make test-e2e
